name: Restart Cloudtype Server

on:
  schedule:
    - cron: "0 */23 * * *"  # 매 23시간마다 실행
  workflow_dispatch:  # 수동 실행

jobs:
  restart-cloudtype:
    runs-on: ubuntu-latest

    steps:
      # Python 환경 설정
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      # Selenium 및 필요한 패키지 설치
      - name: Install dependencies
        run: |
          pip install selenium

      # Chrome 및 ChromeDriver 설치
      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          # 특정 버전의 Chrome 설치 (114.0.5735.90)
          wget -q https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_114.0.5735.90-1_amd64.deb -O google-chrome-stable.deb
          sudo dpkg -i google-chrome-stable.deb || sudo apt-get -f install -y
          # ChromeDriver 설치 (114.0.5735.90)
          wget -q "https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip" -O chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          rm chromedriver_linux64.zip google-chrome-stable.deb

      # Selenium 스크립트 실행
      - name: Restart Cloudtype Server
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
        run: python restart-cloudtype.py
